#ifndef AUDIOMETADATA_H
#define AUDIOMETADATA_H

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// clang-format off
//// {---- Generated by Gemini : START ---- ////
static const int bitrates[16] = {0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320, 0};

static uint32_t read_u32_be(FILE *fp) {
    uint8_t b[4];
    if (fread(b, 1, 4, fp) < 4) return 0;
    return (uint32_t)((b[0] << 24) | (b[1] << 16) | (b[2] << 8) | b[3]);
}

static char* convert_to_utf8(unsigned char *data, int len) {
    if (len <= 0) return strdup("");
    unsigned char encoding = data[0];
    unsigned char *ptr = data + 1;
    int size = len - 1;
    char *result = malloc(size * 3 + 1);
    int out = 0;
    if (encoding == 0x01 || encoding == 0x02) {
        int le = (encoding == 0x01);
        if (size >= 2) {
            if (ptr[0] == 0xFF && ptr[1] == 0xFE) { le = 1; ptr += 2; size -= 2; }
            else if (ptr[0] == 0xFE && ptr[1] == 0xFF) { le = 0; ptr += 2; size -= 2; }
        }
        for (int i = 0; i + 1 < size; i += 2) {
            unsigned int cp = le ? (ptr[i+1] << 8) | ptr[i] : (ptr[i] << 8) | ptr[i+1];
            if (cp < 0x80) result[out++] = cp;
            else if (cp < 0x800) { result[out++] = (0xC0|(cp>>6)); result[out++] = (0x80|(cp&0x3F)); }
            else { result[out++] = (0xE0|(cp>>12)); result[out++] = (0x80|((cp>>6)&0x3F)); result[out++] = (0x80|(cp&0x3F)); }
        }
    } else if (encoding == 0x00) {
        for (int i = 0; i < size; i++) {
            if (ptr[i] < 128) { if (ptr[i] >= 32) result[out++] = ptr[i]; }
            else { result[out++] = (0xC0 | (ptr[i] >> 6)); result[out++] = (0x80 | (ptr[i] & 0x3F)); }
        }
    } else {
        for (int i = 0; i < size; i++) if (ptr[i] >= 32) result[out++] = ptr[i];
    }
    result[out] = '\0';
    return result;
}

static char* get_mp3_duration(const char *filename) {
    FILE *fp = fopen(filename, "rb");
    if (!fp) return NULL;
    fseek(fp, 0, SEEK_END);
    long file_size = ftell(fp);
    rewind(fp);
    unsigned char h[10];
    int id3_size = 0;
    if (fread(h, 1, 10, fp) == 10 && memcmp(h, "ID3", 3) == 0) {
        id3_size = ((h[6] << 21) | (h[7] << 14) | (h[8] << 7) | h[9]) + 10;
        fseek(fp, id3_size, SEEK_SET);
    } else rewind(fp);
    unsigned char frame[4];
    char *res = NULL;
    while (fread(frame, 1, 1, fp) == 1) {
        if (frame[0] == 0xFF) {
            if (fread(frame + 1, 1, 3, fp) < 3) break;
            if ((frame[1] & 0xE0) == 0xE0) {
                int br_idx = (frame[2] >> 4) & 0x0F;
                int bitrate = bitrates[br_idx];
                if (bitrate > 0) {
                    int seconds = (int)(((file_size - id3_size) * 8.0) / (bitrate * 1000.0));
                    res = malloc(16);
                    snprintf(res, 16, "%d:%02d", seconds / 60, seconds % 60);
                }
                break;
            }
        }
    }
    fclose(fp);
    return res;
}

static char** get_mp3_metadata(const char *filename) {
    FILE *fp = fopen(filename, "rb");
    if (!fp) return NULL;
    unsigned char h[10];
    int has_v2 = (fread(h, 1, 10, fp) == 10 && memcmp(h, "ID3", 3) == 0);
    int has_v1 = 0;
    if (!has_v2) {
        fseek(fp, -128, SEEK_END);
        char v1_tag[3];
        if (fread(v1_tag, 1, 3, fp) == 3 && memcmp(v1_tag, "TAG", 3) == 0) has_v1 = 1;
    }
    if (!has_v2 && !has_v1) { fclose(fp); return NULL; }
    char **tags = malloc(sizeof(char*) * 4);
    for(int i=0; i<4; i++) tags[i] = strdup("");
    if (has_v2) {
        int total = (h[6] << 21) | (h[7] << 14) | (h[8] << 7) | h[9];
        int proc = 0;
        while (proc < total) {
            unsigned char f[10];
            if (fread(f, 1, 10, fp) < 10) break;
            proc += 10;
            unsigned int fs = (f[4] << 24) | (f[5] << 16) | (f[6] << 8) | f[7];
            if (f[0] == 0 || fs == 0 || fs > (unsigned int)total) break;
            unsigned char *buf = malloc(fs);
            fread(buf, 1, fs, fp);
            proc += fs;
            if (memcmp(f, "TIT2", 4) == 0) { free(tags[0]); tags[0] = convert_to_utf8(buf, fs); }
            else if (memcmp(f, "TPE1", 4) == 0) { free(tags[1]); tags[1] = convert_to_utf8(buf, fs); }
            else if (memcmp(f, "TALB", 4) == 0) { free(tags[2]); tags[2] = convert_to_utf8(buf, fs); }
            else if (memcmp(f, "TYER", 4) == 0 || memcmp(f, "TDRC", 4) == 0) { free(tags[3]); tags[3] = convert_to_utf8(buf, fs); }
            free(buf);
        }
    } else {
        char b[31] = {0};
        fseek(fp, -125, SEEK_END); fread(b, 1, 30, fp); free(tags[0]); tags[0] = strdup(b);
        fseek(fp, -95, SEEK_END); fread(b, 1, 30, fp); free(tags[1]); tags[1] = strdup(b);
        fseek(fp, -65, SEEK_END); fread(b, 1, 30, fp); free(tags[2]); tags[2] = strdup(b);
        fseek(fp, -35, SEEK_END); fread(b, 1, 4, fp); b[4] = '\0'; free(tags[3]); tags[3] = strdup(b);
    }
    fclose(fp);
    return tags;
}

static char* get_aac_duration(const char *filename) {
    FILE *fp = fopen(filename, "rb");
    if (!fp) return NULL;

    unsigned char h[10];
    if (fread(h, 1, 10, fp) == 10 && memcmp(h, "ID3", 3) == 0) {
        int id3_sz = ((h[6] << 21) | (h[7] << 14) | (h[8] << 7) | h[9]) + 10;
        fseek(fp, id3_sz, SEEK_SET);
    } else rewind(fp);

    uint8_t buf[7];
    double total_dur = 0;
    static const int freq[13] = {96000, 88200, 64000, 48000, 44100, 32000, 24000, 22050, 16000, 12000, 11025, 8000, 7350};

    while (fread(buf, 1, 7, fp) == 7) {
        if (buf[0] == 0xFF && (buf[1] & 0xF0) == 0xF0) {
            int f_idx = (buf[2] & 0x3C) >> 2;
            int f_size = ((buf[3] & 0x03) << 11) | (buf[4] << 3) | ((buf[5] & 0xE0) >> 5);
            if (f_idx < 13) total_dur += 1024.0 / freq[f_idx];
            if (f_size > 7) fseek(fp, f_size - 7, SEEK_CUR);
            else break;
        } else {
            fseek(fp, -6, SEEK_CUR);
        }
    }

    fclose(fp);
    if (total_dur <= 0) return NULL;

    char *res = malloc(16);
    int s = (int)total_dur;
    snprintf(res, 16, "%d:%02d", s / 60, s % 60);
    return res;
}

static char* get_m4a_duration(const char *filename) {
    FILE *fp = fopen(filename, "rb");
    if (!fp) return NULL;
    uint32_t sz, ty;
    while (fread(&sz, 4, 1, fp) == 1) {
        sz = __builtin_bswap32(sz);
        if (fread(&ty, 4, 1, fp) < 1) break;
        if (sz < 8) break;
        if (memcmp(&ty, "moov", 4) == 0) continue; 
        if (memcmp(&ty, "mvhd", 4) == 0) {
            uint8_t v; fread(&v, 1, 1, fp); fseek(fp, 3, SEEK_CUR);
            uint32_t ts, du;
            if (v == 0) {
                fseek(fp, 8, SEEK_CUR);
                ts = read_u32_be(fp);
                du = read_u32_be(fp);
            } else {
                fseek(fp, 16, SEEK_CUR);
                ts = read_u32_be(fp);
                fseek(fp, 4, SEEK_CUR);
                du = read_u32_be(fp);
            }
            fclose(fp);
            if (ts == 0) return NULL;
            char *r = malloc(16);
            snprintf(r, 16, "%d:%02d", (du/ts)/60, (du/ts)%60);
            return r;
        }
        fseek(fp, sz - 8, SEEK_CUR);
    }
    fclose(fp);
    return NULL;
}

static char** get_m4a_metadata(const char *filename) {
    FILE *fp = fopen(filename, "rb");
    if (!fp) return NULL;

    char **tags = malloc(sizeof(char*) * 4);
    for(int i=0; i<4; i++) tags[i] = strdup("");
    int found = 0;

    uint32_t sz;
    char ty[4];

    while (fread(&sz, 4, 1, fp) == 1) {
        sz = __builtin_bswap32(sz);
        if (fread(ty, 1, 4, fp) < 4) break;

        if (memcmp(ty, "moov", 4) == 0 || memcmp(ty, "udta", 4) == 0 || memcmp(ty, "ilst", 4) == 0) {
            continue;
        }
        if (memcmp(ty, "meta", 4) == 0) {
            fseek(fp, 4, SEEK_CUR);
            continue;
        }

        int idx = -1;
        if      (memcmp(ty, "\xA9" "nam", 4) == 0) idx = 0;
        else if (memcmp(ty, "\xA9" "ART", 4) == 0) idx = 1;
        else if (memcmp(ty, "\xA9" "alb", 4) == 0) idx = 2;
        else if (memcmp(ty, "\xA9" "day", 4) == 0) idx = 3;

        if (idx != -1) {
            uint32_t sub_sz = read_u32_be(fp);
            char sub_ty[4];
            if (fread(sub_ty, 1, 4, fp) == 4 && memcmp(sub_ty, "data", 4) == 0) {
                fseek(fp, 8, SEEK_CUR);
                int tlen = sub_sz - 16;
                if (tlen > 0 && tlen < 4096) {
                    free(tags[idx]);
                    tags[idx] = malloc(tlen + 1);
                    fread(tags[idx], 1, tlen, fp);
                    tags[idx][tlen] = '\0';
                    found = 1;
                }
            }
            if (sz > 8) fseek(fp, (sz - 8) - (sub_sz ? sub_sz : 0), SEEK_CUR);
        } else {
            if (sz < 8) break;
            if (fseek(fp, sz - 8, SEEK_CUR) != 0) break;
        }
    }

    fclose(fp);
    if (!found) {
        for(int i=0; i<4; i++) free(tags[i]);
        free(tags);
        return NULL;
    }
    return tags;
}

static char* get_flac_duration(const char *filename) {
    FILE *fp = fopen(filename, "rb");
    if (!fp) return NULL;

    char header[4];
    if (fread(header, 1, 4, fp) < 4 || memcmp(header, "fLaC", 4) != 0) {
        fclose(fp); return NULL;
    }

    uint8_t buf[34]; 
    if (fread(buf, 1, 4, fp) == 4) {
        int type = buf[0] & 0x7F;
        uint32_t size = (buf[1] << 16) | (buf[2] << 8) | buf[3];
        
        if (type == 0 && size >= 34) {
            fread(buf, 1, 34, fp);
            uint32_t sample_rate = (buf[10] << 12) | (buf[11] << 4) | (buf[12] >> 4);
            uint64_t total_samples = ((uint64_t)(buf[13] & 0x0F) << 32) | 
                                     ((uint64_t)buf[14] << 24) | 
                                     ((uint64_t)buf[15] << 16) | 
                                     ((uint64_t)buf[16] << 8) | buf[17];

            if (sample_rate > 0) {
                int sec = (int)(total_samples / sample_rate);
                char *res = malloc(16);
                snprintf(res, 16, "%d:%02d", sec / 60, sec % 60);
                fclose(fp);
                return res;
            }
        }
    }

    fclose(fp);
    return NULL;
}

static char** get_flac_metadata(const char *filename) {
    FILE *fp = fopen(filename, "rb");
    if (!fp) return NULL;

    char header[4];
    if (fread(header, 1, 4, fp) < 4 || memcmp(header, "fLaC", 4) != 0) {
        fclose(fp); return NULL;
    }

    char **tags = malloc(sizeof(char*) * 4);
    for(int i=0; i<4; i++) tags[i] = strdup("");
    int found_any = 0;

    int last_block = 0;
    while (!last_block) {
        uint8_t block_header[4];
        if (fread(block_header, 1, 4, fp) < 4) break;

        last_block = block_header[0] & 0x80;
        int type = block_header[0] & 0x7F;
        uint32_t size = (block_header[1] << 16) | (block_header[2] << 8) | block_header[3];

        if (type == 4) {
            uint32_t vendor_len;
            fread(&vendor_len, 4, 1, fp);
            fseek(fp, vendor_len, SEEK_CUR);

            uint32_t comment_list_len;
            fread(&comment_list_len, 4, 1, fp);

            for (uint32_t i = 0; i < comment_list_len; i++) {
                uint32_t comm_len;
                fread(&comm_len, 4, 1, fp);
                char *comm = malloc(comm_len + 1);
                fread(comm, 1, comm_len, fp);
                comm[comm_len] = '\0';

                if (strncasecmp(comm, "TITLE=", 6) == 0) { free(tags[0]); tags[0] = strdup(comm + 6); found_any = 1; }
                else if (strncasecmp(comm, "ARTIST=", 7) == 0) { free(tags[1]); tags[1] = strdup(comm + 7); found_any = 1; }
                else if (strncasecmp(comm, "ALBUM=", 6) == 0) { free(tags[2]); tags[2] = strdup(comm + 6); found_any = 1; }
                else if (strncasecmp(comm, "DATE=", 5) == 0) { free(tags[3]); tags[3] = strdup(comm + 5); found_any = 1; }
                
                free(comm);
            }
            break; 
        } else {
            fseek(fp, size, SEEK_CUR);
        }
    }

    fclose(fp);
    if (!found_any) { for(int i=0; i<4; i++) free(tags[i]); free(tags); return NULL; }
    return tags;
}

static char* get_wav_duration(const char *filename) {
    FILE *fp = fopen(filename, "rb");
    if (!fp) return NULL;

    char chunk_id[4];
    uint32_t chunk_sz;
    uint32_t byte_rate = 0;
    uint32_t data_sz = 0;

    fseek(fp, 12, SEEK_SET); 
    while (fread(chunk_id, 1, 4, fp) == 4) {
        fread(&chunk_sz, 4, 1, fp);
        if (memcmp(chunk_id, "fmt ", 4) == 0) {
            fseek(fp, 8, SEEK_CUR); 
            fread(&byte_rate, 4, 1, fp);
            fseek(fp, chunk_sz - 12, SEEK_CUR);
        } else if (memcmp(chunk_id, "data", 4) == 0) {
            data_sz = chunk_sz;
            break; 
        } else {
            fseek(fp, chunk_sz, SEEK_CUR);
        }
    }
    fclose(fp);

    if (byte_rate > 0 && data_sz > 0) {
        int sec = data_sz / byte_rate;
        char *res = malloc(16);
        snprintf(res, 16, "%d:%02d", sec / 60, sec % 60);
        return res;
    }
    return NULL;
}

static char** get_wav_metadata(const char *filename) {
    FILE *fp = fopen(filename, "rb");
    if (!fp) return NULL;

    fseek(fp, 12, SEEK_SET);
    char **tags = malloc(sizeof(char*) * 4);
    for(int i=0; i<4; i++) tags[i] = strdup("");
    int found = 0;

    uint32_t chunk_sz;
    char chunk_id[4];
    while (fread(chunk_id, 1, 4, fp) == 4) {
        fread(&chunk_sz, 4, 1, fp);
        if (memcmp(chunk_id, "LIST", 4) == 0) {
            char list_type[4];
            fread(list_type, 1, 4, fp);
            if (memcmp(list_type, "INFO", 4) == 0) {
                long end = ftell(fp) + chunk_sz - 4;
                while (ftell(fp) < end) {
                    char sub_id[4];
                    uint32_t sub_sz;
                    fread(sub_id, 1, 4, fp);
                    fread(&sub_sz, 4, 1, fp);
                    
                    int idx = -1;
                    if      (memcmp(sub_id, "INAM", 4) == 0) idx = 0;
                    else if (memcmp(sub_id, "IART", 4) == 0) idx = 1;
                    else if (memcmp(sub_id, "IPRD", 4) == 0) idx = 2;
                    else if (memcmp(sub_id, "ICRD", 4) == 0) idx = 3;

                    if (idx != -1) {
                        free(tags[idx]);
                        tags[idx] = malloc(sub_sz + 1);
                        fread(tags[idx], 1, sub_sz, fp);
                        tags[idx][sub_sz] = '\0';
                        found = 1;
                    } else fseek(fp, sub_sz, SEEK_CUR);
                    
                    if (sub_sz % 2 != 0) fseek(fp, 1, SEEK_CUR);
                }
            } else fseek(fp, chunk_sz - 4, SEEK_CUR);
        } else fseek(fp, chunk_sz, SEEK_CUR);
    }
    fclose(fp);
    if (!found) { for(int i=0; i<4; i++) free(tags[i]); free(tags); return NULL; }
    return tags;
}

static char* get_ogg_duration(const char *filename) {
    FILE *fp = fopen(filename, "rb");
    if (!fp) return NULL;

    uint32_t sample_rate = 0;
    uint64_t max_granule = 0;
    uint8_t buf[4096];
    size_t bytes_read;

    while ((bytes_read = fread(buf, 1, sizeof(buf), fp)) > 0) {
        for (size_t i = 0; i < bytes_read - 12; i++) {
            // 1. Sync and Granule (Same for all Ogg)
            if (buf[i] == 'O' && buf[i+1] == 'g' && buf[i+2] == 'g' && buf[i+3] == 'S') {
                uint64_t current_granule;
                memcpy(&current_granule, &buf[i + 6], 8);
                if (current_granule != (uint64_t)-1 && current_granule > max_granule) {
                    max_granule = current_granule;
                }
            }
            
            // 2. Check for Vorbis ID (\x01vorbis)
            if (sample_rate == 0 && buf[i] == 0x01 && memcmp(&buf[i+1], "vorbis", 6) == 0) {
                if (i + 12 + 4 <= bytes_read) memcpy(&sample_rate, &buf[i + 12], 4);
            }
            
            // 3. Check for Opus ID (OpusHead)
            if (sample_rate == 0 && memcmp(&buf[i], "OpusHead", 8) == 0) {
                sample_rate = 48000; // Opus timing is always 48kHz
            }
        }
        if (bytes_read == sizeof(buf)) fseek(fp, -12, SEEK_CUR);
    }

    fclose(fp);
    if (sample_rate == 0 || max_granule == 0) return NULL;

    int sec = (int)(max_granule / sample_rate);
    char *res = malloc(16);
    snprintf(res, 16, "%d:%02d", sec / 60, sec % 60);
    return res;
}

static char** get_ogg_metadata(const char *filename) {
    FILE *fp = fopen(filename, "rb");
    if (!fp) return NULL;
    char **tags = malloc(sizeof(char*) * 4);
    for(int i=0; i<4; i++) tags[i] = strdup("");
    int found_any = 0;
    
    uint8_t buf[4096];
    size_t bytes_read = fread(buf, 1, sizeof(buf), fp);
    
    for (size_t i = 0; i < bytes_read - 12; i++) {
        int is_vorbis = (buf[i] == 0x03 && memcmp(&buf[i+1], "vorbis", 6) == 0);
        int is_opus   = (memcmp(&buf[i], "OpusTags", 8) == 0);

        if (is_vorbis || is_opus) {
            // Seek to the start of the actual comment data
            // Vorbis: 1 (type) + 6 (sig) = 7 bytes
            // Opus: 8 (sig) = 8 bytes
            fseek(fp, i + (is_vorbis ? 7 : 8), SEEK_SET);

            uint32_t vendor_len;
            fread(&vendor_len, 4, 1, fp);
            fseek(fp, vendor_len, SEEK_CUR);

            uint32_t list_len;
            fread(&list_len, 4, 1, fp);
            for (uint32_t j = 0; j < list_len; j++) {
                uint32_t c_len;
                fread(&c_len, 4, 1, fp);
                if (c_len > 5000) break;
                char *c = malloc(c_len + 1);
                fread(c, 1, c_len, fp);
                c[c_len] = '\0';

                if      (strncasecmp(c, "TITLE=", 6) == 0)  { free(tags[0]); tags[0] = strdup(c + 6); found_any = 1; }
                else if (strncasecmp(c, "ARTIST=", 7) == 0) { free(tags[1]); tags[1] = strdup(c + 7); found_any = 1; }
                else if (strncasecmp(c, "ALBUM=", 6) == 0)  { free(tags[2]); tags[2] = strdup(c + 6); found_any = 1; }
                else if (strncasecmp(c, "DATE=", 5) == 0)   { free(tags[3]); tags[3] = strdup(c + 5); found_any = 1; }
                free(c);
            }
            break;
        }
    }

    fclose(fp);
    if (!found_any) { for(int i=0; i<4; i++) free(tags[i]); free(tags); return NULL; }
    return tags;
}

static char* get_3gp_duration(const char *filename) {
    FILE *fp = fopen(filename, "rb");
    if (!fp) return NULL;

    uint32_t timescale = 0;
    uint32_t duration = 0;
    uint8_t buf[8];

    while (fread(buf, 1, 4, fp) == 4) {
        uint32_t sz = (buf[0] << 24) | (buf[1] << 16) | (buf[2] << 8) | buf[3];
        char type[4];
        fread(type, 1, 4, fp);

        if (memcmp(type, "mvhd", 4) == 0) {
            fseek(fp, 12, SEEK_CUR);
            fread(&timescale, 4, 1, fp);
            fread(&duration, 4, 1, fp);
            timescale = __builtin_bswap32(timescale);
            duration = __builtin_bswap32(duration);
            break;
        }
        fseek(fp, sz - 8, SEEK_CUR);
    }
    fclose(fp);

    if (timescale > 0) {
        int sec = duration / timescale;
        char *res = malloc(16);
        snprintf(res, 16, "%d:%02d", sec / 60, sec % 60);
        return res;
    }
    return NULL;
}

static char** get_3gp_metadata(const char *filename) {
    return get_m4a_metadata(filename); 
}

static char** get_metadata_universal(const char *filename) {
    const char *ext = strrchr(filename, '.');
    if (!ext) return NULL;
    if (strcasecmp(ext, ".3gp") == 0)  return get_3gp_metadata(filename);
    if (strcasecmp(ext, ".flac") == 0) return get_flac_metadata(filename);
    if (strcasecmp(ext, ".m4a") == 0)  return get_m4a_metadata(filename);
    if (strcasecmp(ext, ".mp3") == 0)  return get_mp3_metadata(filename);
    if (strcasecmp(ext, ".ogg") == 0)  return get_ogg_metadata(filename);
    if (strcasecmp(ext, ".opus") == 0) return get_ogg_metadata(filename);
    if (strcasecmp(ext, ".wav") == 0)  return get_wav_metadata(filename);
    return NULL;
}

static char* get_duration_universal(const char *filename) {
    const char *ext = strrchr(filename, '.');
    if (!ext) return NULL;
    if (strcasecmp(ext, ".3gp") == 0)  return get_3gp_duration(filename);
    if (strcasecmp(ext, ".aac") == 0)  return get_aac_duration(filename);
    if (strcasecmp(ext, ".flac") == 0) return get_flac_duration(filename);
    if (strcasecmp(ext, ".m4a") == 0)  return get_m4a_duration(filename);
    if (strcasecmp(ext, ".mp3") == 0)  return get_mp3_duration(filename);
    if (strcasecmp(ext, ".ogg") == 0)  return get_ogg_duration(filename);
    if (strcasecmp(ext, ".opus") == 0) return get_ogg_duration(filename);
    if (strcasecmp(ext, ".wav") == 0)  return get_wav_duration(filename);
    return NULL;
}
//// ---- Generated by Gemini : END ----} ////

#endif
